### ISSUE TITLE
Removing nbpresent

### ISSUE THREAD

**Issue by wassimseif** [Anaconda-Platform/nb_conda#62]
Hello
I just installed this using `conda install nb_conda` and I'm getting this menu from `nbpresent` for some options
<img width="601" alt="screen shot 2017-10-28 at 10 51 28 pm" src="https://user-images.githubusercontent.com/7282773/32137956-b8bb3aec-bc32-11e7-9a41-65f17faf6bd8.png">
is there anyway to install nb_conda without nbpresent?

**Comment by damianavila** [comment]
You can install nb_conda from conda-forge to avoid the installation of the whole set of extensions.

**Comment by wassimseif** [comment]
Is there any reason that nbpresent is installed with nb_conda ?

**Comment by damianavila** [comment]
In the past nbpresent was installed alongside with other nbextension as a bundle because of some issues between the anaconda distribution and the post installation enabling process. And the bundle was the workaround for that. Right know the the anaconda distribution does not ship the extension by default anymore but still the installation from the default repos is being done as a bundle.
